account_controllers:
  resource: '../src/Component/Account/Communication/Controller'
  type: annotation
user_controllers:
  resource: '../src/Component/User/Communication/Controller'
  type: annotation
home_controllers:
  resource: '../src/Component/Home/Communication/Controller'
  type: annotation
